# Generated by Django 4.2.11 on 2026-05-05 14:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome da Empresa')),
                ('address', models.CharField(max_length=255, verbose_name='Morada')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('phone', models.CharField(max_length=50, verbose_name='Telefone')),
                ('whatsapp', models.CharField(blank=True, max_length=50, null=True, verbose_name='WhatsApp')),
                ('nif', models.CharField(blank=True, max_length=20, null=True, verbose_name='NIF')),
                ('schedule', models.TextField(verbose_name='Horário de Funcionamento')),
                ('google_maps_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='Link do Google Maps')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição da Empresa')),
            ],
            options={
                'verbose_name': 'Informação do Negócio',
                'verbose_name_plural': 'Informação do Negócio',
            },
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome da Categoria')),
                ('order', models.IntegerField(default=0, verbose_name='Ordem')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StaffMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('role', models.CharField(max_length=100, verbose_name='Cargo')),
                ('avatar_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='URL da Fotografia')),
            ],
            options={
                'verbose_name': 'Membro da Equipa',
                'verbose_name_plural': 'Equipa',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100, verbose_name='Nome do Cliente')),
                ('text', models.TextField(verbose_name='Testemunho')),
                ('rating', models.IntegerField(default=5, verbose_name='Classificação (1 a 5)')),
            ],
            options={
                'verbose_name': 'Testemunho',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Utilizador',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome do Serviço')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Preço')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.servicecategory', verbose_name='Categoria')),
            ],
            options={
                'ordering': ['category__order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data da Marcação')),
                ('time', models.TimeField(verbose_name='Hora da Marcação')),
                ('status', models.CharField(choices=[('Pendente', 'Pendente'), ('Confirmada', 'Confirmada'), ('Cancelada', 'Cancelada')], default='Pendente', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.service', verbose_name='Serviço')),
                ('staff_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.staffmember', verbose_name='Especialista (Opcional)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
            ],
            options={
                'ordering': ['-date', '-time'],
            },
        ),
    ]
