# Generated by Django 4.2.11 on 2026-09-28 11:45

import datetime
from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome da Empresa')),
                ('address', models.CharField(max_length=255, verbose_name='Morada')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('phone', models.CharField(max_length=50, verbose_name='Telefone')),
                ('whatsapp', models.CharField(blank=True, max_length=50, null=True, verbose_name='WhatsApp')),
                ('nif', models.CharField(blank=True, max_length=20, null=True, verbose_name='NIF')),
                ('schedule', models.TextField(verbose_name='Horário de Funcionamento')),
                ('opening_time', models.TimeField(default=datetime.time(9, 0), verbose_name='Hora de Abertura')),
                ('closing_time', models.TimeField(default=datetime.time(19, 0), verbose_name='Hora de Fecho')),
                ('lunch_start', models.TimeField(blank=True, null=True, verbose_name='Início Almoço')),
                ('lunch_end', models.TimeField(blank=True, null=True, verbose_name='Fim Almoço')),
                ('google_maps_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='Link do Google Maps')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição da Empresa')),
                ('cancel_limit_hours', models.IntegerField(default=24, verbose_name='Horas limite para cancelamento (Ex: 24 para 24h antes)')),
            ],
            options={
                'verbose_name': 'Informação do Negócio',
                'verbose_name_plural': 'Informação do Negócio',
                'db_table': 'business_info',
            },
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome da Categoria')),
                ('order', models.IntegerField(default=0, verbose_name='Ordem')),
            ],
            options={
                'verbose_name': 'Categoria de Serviço',
                'verbose_name_plural': 'Categorias de Serviços',
                'db_table': 'service_categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StaffMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('role', models.CharField(max_length=100, verbose_name='Cargo')),
                ('avatar_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='URL da Fotografia')),
            ],
            options={
                'verbose_name': 'Membro da Equipa',
                'verbose_name_plural': 'Equipa',
                'db_table': 'staff_members',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100, verbose_name='Nome do Cliente')),
                ('text', models.TextField(verbose_name='Testemunho')),
                ('rating', models.IntegerField(default=5, verbose_name='Classificação (1 a 5)')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Visível no Site')),
            ],
            options={
                'verbose_name': 'Testemunho',
                'verbose_name_plural': 'Testemunhos',
                'db_table': 'testimonials',
            },
        ),
        migrations.CreateModel(
            name='Utilizador',
            fields=[
            ],
            options={
                'verbose_name': 'Utilizador',
                'verbose_name_plural': 'Utilizadores',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Utilizador',
                'db_table': 'user_profiles',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome do Serviço')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Preço')),
                ('duration', models.IntegerField(default=30, verbose_name='Duração (minutos)')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.servicecategory', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Serviço',
                'verbose_name_plural': 'Serviços',
                'db_table': 'services',
                'ordering': ['category__order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data da Marcação')),
                ('time', models.TimeField(verbose_name='Hora da Marcação (Início)')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='Hora de Fim Estimada')),
                ('status', models.CharField(choices=[('Pendente', 'Pendente'), ('Confirmada', 'Confirmada'), ('Cancelada', 'Cancelada')], default='Pendente', max_length=20)),
                ('cancellation_reason', models.CharField(blank=True, max_length=100, null=True, verbose_name='Motivo do Cancelamento')),
                ('cancellation_notes', models.TextField(blank=True, null=True, verbose_name='Notas de Cancelamento')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.service', verbose_name='Serviço')),
                ('staff_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.staffmember', verbose_name='Especialista (Opcional)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Marcação',
                'verbose_name_plural': 'Marcações',
                'db_table': 'appointments',
                'ordering': ['-date', '-time'],
            },
        ),
    ]
