# Generated by Django 4.2.11 on 2026-09-28 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Confirmada', 'Confirmada'), ('Concluída', 'Concluída'), ('Faltou', 'Faltou (No-Show)'), ('Cancelada', 'Cancelada')], default='Pendente', max_length=20),
        ),
    ]
