# Generated by Django 4.2.11 on 2026-08-09 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['-date', '-time'], 'verbose_name': 'Marcação', 'verbose_name_plural': 'Marcações'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['category__order', 'name'], 'verbose_name': 'Serviço', 'verbose_name_plural': 'Serviços'},
        ),
        migrations.AlterModelOptions(
            name='servicecategory',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Categoria de Serviço', 'verbose_name_plural': 'Categorias de Serviços'},
        ),
        migrations.AlterModelOptions(
            name='testimonial',
            options={'verbose_name': 'Testemunho', 'verbose_name_plural': 'Testemunhos'},
        ),
    ]
