# Generated by Django 6.1.1 on 2026-09-23 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_appointment_options_alter_service_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='is_visible',
            field=models.BooleanField(default=True, verbose_name='Visível no Site'),
        ),
    ]
