# Generated by Django 5.2.17 on 2026-09-29 19:02

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_appointment_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessOpeningHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, 'Segunda-feira'), (1, 'Terça-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira'), (5, 'Sábado'), (6, 'Domingo')], verbose_name='Dia da Semana')),
                ('is_open', models.BooleanField(default=True, verbose_name='Aberto?')),
                ('opening_time', models.TimeField(default='09:00:00', verbose_name='Hora de Abertura')),
                ('closing_time', models.TimeField(default='19:00:00', verbose_name='Hora de Fecho')),
                ('lunch_start', models.TimeField(blank=True, null=True, verbose_name='Início Almoço')),
                ('lunch_end', models.TimeField(blank=True, null=True, verbose_name='Fim Almoço')),
            ],
            options={
                'verbose_name': 'Horário por Dia',
                'verbose_name_plural': 'Horários por Dia',
                'db_table': 'business_opening_hours',
                'ordering': ['weekday'],
            },
        ),
        migrations.AlterModelOptions(
            name='testimonial',
            options={'ordering': ['-created_at'], 'verbose_name': 'Testemunho', 'verbose_name_plural': 'Testemunhos'},
        ),
        migrations.AddField(
            model_name='appointment',
            name='duration_at_booking',
            field=models.IntegerField(blank=True, null=True, verbose_name='Duração em minutos (ao marcar)'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='price_at_booking',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Preço (ao marcar)'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='service_name_at_booking',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Serviço (ao marcar)'),
        ),
        migrations.AddField(
            model_name='service',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ativo para novas marcações?'),
        ),
        migrations.AddField(
            model_name='staffmember',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ativo para novas marcações?'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Submissão'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testimonials', to=settings.AUTH_USER_MODEL, verbose_name='Utilizador'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='privacy_policy_accepted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Política de Privacidade Aceite Em'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='terms_accepted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Termos Aceites Em'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='website.service', verbose_name='Serviço'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='staff_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.staffmember', verbose_name='Especialista'),
        ),
        migrations.AlterField(
            model_name='businessinfo',
            name='cancel_limit_hours',
            field=models.IntegerField(default=24, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(168)], verbose_name='Horas limite para cancelamento (Ex: 24 para 24h antes)'),
        ),
        migrations.AlterField(
            model_name='businessinfo',
            name='closing_time',
            field=models.TimeField(default='19:00:00', verbose_name='Hora de Fecho Padrão'),
        ),
        migrations.AlterField(
            model_name='businessinfo',
            name='opening_time',
            field=models.TimeField(default='09:00:00', verbose_name='Hora de Abertura Padrão'),
        ),
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='website.servicecategory', verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='service',
            name='duration',
            field=models.IntegerField(default=30, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(480)], verbose_name='Duração (minutos)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Preço'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='is_visible',
            field=models.BooleanField(default=False, verbose_name='Visível no Site (Moderado)'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='rating',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Classificação (1 a 5)'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['date', 'staff_member', 'status'], name='idx_appt_date_staff_status'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['user', 'date'], name='idx_appt_user_date'),
        ),
        migrations.AddConstraint(
            model_name='businessinfo',
            constraint=models.CheckConstraint(condition=models.Q(('cancel_limit_hours__gte', 0)), name='business_cancel_limit_positive'),
        ),
        migrations.AddConstraint(
            model_name='service',
            constraint=models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='service_price_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='service',
            constraint=models.CheckConstraint(condition=models.Q(('duration__gt', 0)), name='service_duration_positive'),
        ),
        migrations.AddConstraint(
            model_name='testimonial',
            constraint=models.CheckConstraint(condition=models.Q(('rating__gte', 1), ('rating__lte', 5)), name='testimonial_rating_range'),
        ),
        migrations.AddField(
            model_name='businessopeninghours',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opening_hours', to='website.businessinfo'),
        ),
        migrations.AlterUniqueTogether(
            name='businessopeninghours',
            unique_together={('business', 'weekday')},
        ),
    ]
