# Generated by Django 4.2.30 on 2026-05-04 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessinfo',
            name='nif',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='NIF'),
        ),
    ]
