# Generated by Django 5.2.17 on 2026-09-30 10:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def check_and_update_data(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    BusinessOpeningHours = apps.get_model('website', 'BusinessOpeningHours')
    
    # 1. Verificação de integridade para emails duplicados
    from django.db.models.functions import Lower
    from django.db.models import Count
    dups = (
        User.objects.exclude(email='')
        .annotate(email_lower=Lower('email'))
        .values('email_lower')
        .annotate(cnt=Count('id'))
        .filter(cnt__gt=1)
    )
    if dups.exists():
        dup_list = [d['email_lower'] for d in dups]
        raise Exception(
            f"ERRO DE INTEGRIDADE: Existem emails duplicados na base de dados que impedem "
            f"a criação do índice único insensível a maiúsculas: {dup_list}."
        )

    # 2. Issue 22: Quarta-feira (weekday=2) e Domingo (weekday=6) encerrados por omissão
    # para preservar o comportamento histórico do negócio
    BusinessOpeningHours.objects.filter(weekday__in=[2, 6]).update(is_open=False)


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_backfill_snapshots_and_hours'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(check_and_update_data, migrations.RunPython.noop),
        migrations.RunSQL(
            sql="CREATE UNIQUE INDEX IF NOT EXISTS unique_user_email_ci ON auth_user (LOWER(email)) WHERE email != '';",
            reverse_sql="DROP INDEX IF EXISTS unique_user_email_ci;"
        ),
        migrations.RemoveConstraint(
            model_name='businessinfo',
            name='business_cancel_limit_positive',
        ),
        migrations.RemoveConstraint(
            model_name='service',
            name='service_duration_positive',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='staff_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='website.staffmember', verbose_name='Especialista'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Confirmada', 'Confirmada'), ('Aguardando Fecho', 'Aguardando Fecho'), ('Concluída', 'Concluída'), ('Faltou', 'Faltou (No-Show)'), ('Cancelada', 'Cancelada')], default='Pendente', max_length=20),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Cliente'),
        ),
        migrations.AddConstraint(
            model_name='businessinfo',
            constraint=models.CheckConstraint(condition=models.Q(('cancel_limit_hours__gte', 0), ('cancel_limit_hours__lte', 168)), name='business_cancel_limit_range'),
        ),
        migrations.AddConstraint(
            model_name='businessopeninghours',
            constraint=models.CheckConstraint(condition=models.Q(('weekday__gte', 0), ('weekday__lte', 6)), name='opening_hours_weekday_valid'),
        ),
        migrations.AddConstraint(
            model_name='businessopeninghours',
            constraint=models.CheckConstraint(condition=models.Q(('is_open', False), ('opening_time__lt', models.F('closing_time')), _connector='OR'), name='opening_hours_time_order'),
        ),
        migrations.AddConstraint(
            model_name='service',
            constraint=models.CheckConstraint(condition=models.Q(('duration__gte', 5), ('duration__lte', 480)), name='service_duration_valid'),
        ),
    ]
