# Generated by Django 4.2.11 on 2026-09-24 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_utilizador'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='cancellation_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notas de Cancelamento'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='cancellation_reason',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Motivo do Cancelamento'),
        ),
    ]
