# Generated by Django 5.2.17 on 2026-09-30 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_remove_businessinfo_business_cancel_limit_positive_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='businessopeninghours',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('lunch_start__isnull', True), ('lunch_end__isnull', True)), models.Q(('lunch_start__isnull', False), ('lunch_end__isnull', False)), _connector='OR'), name='opening_hours_lunch_both_or_neither'),
        ),
        migrations.AddConstraint(
            model_name='businessopeninghours',
            constraint=models.CheckConstraint(condition=models.Q(('is_open', False), ('lunch_start__isnull', True), models.Q(('opening_time__lte', models.F('lunch_start')), ('lunch_start__lt', models.F('lunch_end')), ('lunch_end__lte', models.F('closing_time'))), _connector='OR'), name='opening_hours_lunch_within_bounds'),
        ),
    ]
