# Generated by Django 4.2.11 on 2026-09-24 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_appointment_cancellation_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessinfo',
            name='cancel_limit_hours',
            field=models.IntegerField(default=24, verbose_name='Horas limite para cancelamento (Ex: 24 para 24h antes)'),
        ),
    ]
