# Generated by Django 4.2.11 on 2026-09-25 11:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_businessinfo_cancel_limit_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de Fim Estimada'),
        ),
        migrations.AddField(
            model_name='businessinfo',
            name='closing_time',
            field=models.TimeField(default=datetime.time(19, 0), verbose_name='Hora de Fecho'),
        ),
        migrations.AddField(
            model_name='businessinfo',
            name='lunch_end',
            field=models.TimeField(blank=True, null=True, verbose_name='Fim Almoço'),
        ),
        migrations.AddField(
            model_name='businessinfo',
            name='lunch_start',
            field=models.TimeField(blank=True, null=True, verbose_name='Início Almoço'),
        ),
        migrations.AddField(
            model_name='businessinfo',
            name='opening_time',
            field=models.TimeField(default=datetime.time(9, 0), verbose_name='Hora de Abertura'),
        ),
        migrations.AddField(
            model_name='service',
            name='duration',
            field=models.IntegerField(default=30, verbose_name='Duração (minutos)'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.TimeField(verbose_name='Hora da Marcação (Início)'),
        ),
    ]
