# Generated by Django 5.2.17

from django.db import migrations


def preserve_admin_opening_hours(apps, schema_editor):
    """
    Migração de segurança e estabilização de integridade:
    A migração 0005 histórica continha uma atualização forçada de encerramento
    de quartas-feiras e domingos. Esta nova migração corretiva respeita e preserva
    estritamente os valores correntes da base de dados configurados pelos administradores,
    sem aplicar qualquer mutação cega ou reversão destrutiva aos registos existentes de
    BusinessOpeningHours. Ambientes já aplicados devem validar manualmente os seus horários
    caso pretendam reabrir quartas-feiras ou domingos.
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_businessopeninghours_opening_hours_lunch_both_or_neither_and_more'),
    ]

    operations = [
        migrations.RunPython(preserve_admin_opening_hours, migrations.RunPython.noop),
    ]
